apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/namespace-install.yaml

configMapGenerator:
  - name: argocd-cm
    behavior: merge
    files:
    - files/dex.config
    literals:
      - url="https://argocd.okddev.fnal.gov"
  - name: argocd-rbac-cm
    behavior: merge
    files:
    - files/rbac.config.yaml

patchesStrategicMerge:
  - dex-env.yaml

