apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

configMapGenerator:
  - name: argocd-cm
    behavior: merge
    files:
    - files/dex.config

patchesStrategicMerge:
  - dex-env.yaml

